name: Construction API
values:
  - key: baseUrl
    value: 'https://construction-api-2.onrender.com'
    enabled: true
  - key: userId
    value: ''
    enabled: true
  - key: productId
    value: ''
    enabled: true
color: 0
